export const META = {
  title: "비전공자 프론트엔드 개발자 하람의 개발 블로그",
  siteName: "Haram's 개발 블로그",
  description:
    "비전공자 프론트엔드 개발자 하람의 블로그입니다. Frontend 뿐만 아니라, Backend, DevOps, Infra 관련 포스팅을 주로 합니다.",
  keyword: [
    "Frontend",
    "Backend",
    "DevOps",
    "Infra",
    "Next.js",
    "React",
    "TypeScript",
    "Node.js",
    "Python",
    "AWS",
    "Terraform",
    "Jenkins",
    "Github",
    "Developer",
    "프론트엔드",
    "백엔드",
    "인프라",
    "테라폼",
    "젠킨스",
    "개발 블로그",
    "비전공자",
    "개발자",
  ] as string[],
  url: `${process.env.NEXT_PUBLIC_BASE_URL}`,
  ogImage: "/opengraph-image.png",
  googleVerification: process.env.NEXT_PUBLIC_GOOGLE_VERIFICATION,
  naverVerification: process.env.NEXT_PUBLIC_NAVER_VERIFICATION,
} as const;
